CREATE TABLE TJRJ.TJRJ_MOVIMENTO_ITEM_TJ (
    MVIT_DK NUMBER, -- SEQUENCE
    MVIT_PRMV_DK NUMBER,
    MVIT_TP_CHAVE VARCHAR(50),
    MVIT_TP_VALOR VARCHAR(2000)
);
CREATE INDEX MVIT_PRMV_DK_I ON TJRJ.TJRJ_MOVIMENTO_ITEM_TJ (MVIT_PRMV_DK);
CREATE UNIQUE INDEX MVIT_DK_I ON TJRJ.TJRJ_MOVIMENTO_ITEM_TJ (MVIT_DK);
