CREATE TABLE TJRJ_MOVIMENTO_ITEM_TJ (
    MVIT_DK NUMBER, -- SEQUENCE
    MVIT_PRMV_DK NUMBER,
    MVIT_TP_CHAVE nvarchar2(50),
    MVIT_TP_VALOR nvarchar2(2000),
    CONSTRAINT fk_MVIT_PRMV_DK
    FOREIGN KEY (MVIT_PRMV_DK)
    REFERENCES TJRJ_PROCESSO_MOVIMENTO_TJ (PRMV_DK),
    CONSTRAINT PK_MVIT_DK PRIMARY KEY (MVIT_DK)
);
CREATE INDEX MVIT_PRMV_DK_I ON TJRJ_MOVIMENTO_ITEM_TJ (MVIT_PRMV_DK);